### PR TITLE
Adjustments

### PR DESCRIPTION
**Pull request by Stosh12**
I made some updates:

•	Fixed some syntax and HTML tag errors on the Career Oulook pages for proper HTML validity.
•	Fixed responsiveness in the text for the career statistics on the Career Oulook pages.
•	Updated some of the category page’s custom accordion intro description headers with bold text heading starters.
•	Fixed responsiveness with the “Course Hours” column in the category pages custom accordion. This column now sets right aligned near the accordion arrow buttons, as intended.
•	Fixed footer column alignment to work better responsively.
•	Added an @media (min-width: 550px) media query to the CSS to help fix the footer and the Course Hours. I tried to get this fix to work within the existing min-width: 500px media query; but that wasn’t working to well; so, I went back to the original 550px media query.

All in all, there weren’t too may CSS changes to make these fixes happen.

### CODE REVIEW

**Review by Capricornered — COMMENTED** [review]
Most of this looks fine but I'm not sure about the change from 'html lang="en"' to 'html lang="zxx"' on the career outlook pages - from what I understand that would only be used if there isn't any linguistic content on the page.

**Comment by Stosh12** [comment]
Great!

The 'html lang="zxx"' is for the greek text, the Lorem Ipsum. The validator recommends to use that code for pages on which it sees the greek text. I my opinion, this warning comes up inconsistently in the validator; so, I only changed it on the pages for which the validator recommended it being changed. Hence, I believe we have some other pages with greek text; but they haven't tripped the validator. This may be because these pages have a certain amount of text written in the English language on them, as well.

**Comment by Capricornered** [comment]
I think a solution would be to use the "lang" attribute in the "p" tags, so 'p lang="zxx"' wherever there's lorem ipsum. That keeps it from tripping the validator. I feel like the html should be set to "en" if everything else is in English and since the lorem ipsum is intended to be English once the full page is completed, but if it's what the validator recommended anyways then I can go ahead and approve the changes. I might just add a couple fixes to some validation issues I'm getting on my code first before merging so it'll probably be tomorrow before I do.

**Comment by Stosh12** [comment]
I understand and what you’ve written makes sense; however, putting 'p lang="zxx"' into each p tag that has the greeking would be fairly work intensive and somewhat time consuming. Also, I wasn’t aware one could add that attribute to the p tag, only the HTML tag. Interesting… I’m thinking the most efficient way to please the validator and for future designer and/or programmer interaction would be to make that change in the HTML tag. Hence, it’s only one edit or change per page, can be done quickly when it needs changing and keeps our validator happy.

Also, I have some further edits, which I would like to make given the time. The validator likes to error on the HTML for the custom accordions and we have lots of yellow flags on the "br/" tag, which was an older way of writing that tag. It appears the validator is happy with it written this way, "br". Of course, yellow warnings for those tags aren’t considered a critical fix; but if one has time, then it might be good to fix them. I believe I can fix the custom accordion flags fairly easily; but it’ll take some time to edit each HTML page. This is, of course, if I have time to implement these further edits; because exam week is coming up and time will be at a premium. Also, our code check is no-graded, which is a good thing! I held off on these further edits; because of time considerations and also, I didn’t want to change too much all at once.

Will you be making your changes in the adjustments branch or another one, which you’ll create?

**Review by Capricornered — APPROVED** [review]
Going ahead and merging this so I can make the edits to my code as well- I can't find a simple way to pull these changes unless I merge first so I'll probably just create another branch when I'm done.

**Pull request merged**
